name: hello-world

on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.4
      with:
        USERNAME: ubuntu
        HOST: ${{ secrets.HOST }}
        PASSWORD: ${{ secrets.PASSWORD }}
        script: | 
          cd Funny-Discord-Bot/
          git pull
          npm i
          pm2 stop discordBot.js
          pm2 start index.js --name discordBot.js